title: Khoa Bui's Website
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  resume: https://khoabuiv.github.io/Resume.html
  previous_works: https://khoabuiv.github.io/Previous_Works.html
  test: https://khoabuiv.github.io/Fractal_Construction.html
  email: mailto:khoabuiv@gmail.com