title: Khoa Bui's Website
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  resume: https://khoabuiv.github.io/Resume.html
  resume_url: https://drive.google.com/file/d/1taonLlQRpveZIPJm47cyjXB93MG_1tOL/view?usp=sharing
  previous_works: https://khoabuiv.github.io/Previous_Works.html
  stuff_to_share: https://khoabuiv.github.io/another-page.html
  email: mailto:khoabuiv@gmail.com