title: Khoa Bui's Website
description: Khoa Bui
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  resume: https://khoabuiv.github.io/Resume.html
  previous_works: https://khoabuiv.github.io/Academic Works.md
  notes: https://khoabuiv.github.io/Notes.html
  email: mailto:khoabuiv@gmail.com
  test: https://khoabuiv.github.io/another-page.html