title: Khoa Bui's Website
description: Khoa Bui
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  resume: https://khoabuiv.github.io/Resume.html
  academic_works: https://khoabuiv.github.io/academic_works.md
  technical_notes: https://khoabuiv.github.io/Notes.md
  email: mailto:khoabuiv@gmail.com
