title: Khoa Bui's Website
description: Khoa Bui
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  resume: https://khoabuiv.github.io/Resume.html
  linkedin: https://www.linkedin.com/in/khoavanbui/
  risk_calculator: https://khoabuiv.github.io/riskCalculator.html
  academic_works: https://khoabuiv.github.io/academic_works.html
  notes: https://khoabuiv.github.io/notes.html
  email: mailto:khoabuiv@gmail.com
